version: '3.9'
services:
  db:
    image: mysql:latest
    # container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secreto
      MYSQL_DATABASE: wires
      MYSQL_USER: angela
      MYSQL_PASSWORD: secreto
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    build:
      context: .
    # container_name: express-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
